name: this is side name
run-name: this is run name
on: push
jobs:
        
  donwload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: checking can i download artifact
        uses: actions/download-artifact@v4
        with: 
          name: my-art-name
      - name: display
        run: cat setup.js
      - name: ls
        run: ls
        
