name: this is side name
run-name: this is run name
on: push
jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: action/checkout@v4
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: my-art-name
          path: src/test/
