name: myforkflow
run-name: js wf
on: workflow_dispatch
jobs:
    build:
        runs-on: ubuntu-latest
        environment: production
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                node-version: 16
            - name: first step
              run: npm ci
            - name: second step
              run: npm test
                
    second-job:
        runs-on: ubuntu-latest
        steps:
          - name: my name
            run: echo hello world
            

            


            

