name: service container
run-name: service container
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    container: node
    services:
      db:
        image: postgresql
      python:
        image: python
    steps:
      - run: echo "hello world"
      
      
  
